### ISSUE TITLE
LaTeX Error: Option clash for package hyperref.

### ISSUE THREAD

**Issue by Semnodime** [tweh/menukeys#63]
LaTeX Error: Option clash for package hyperref.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.84 \RequirePackage{hyperref}[2010/06/18]
                                        
The package 'hyperref' has already been loaded with options:
  [hidelinks,unicode].
There has now been an attempt to load it with no options. 
Adding the global options:
  'hidelinks,unicode'
to your \documentclass declaration may fix this.

**Comment by Skillmon** [comment]
Can you please provide a minimal document that throws this error? This issue shouldn't be caused by up-to-date `menukeys` versions (so I have no idea where the real issue is).

In older versions of `menukeys` it was advised to load `menukeys` after `hyperref` (this is not necessary with recent versions). So if you're on an older version, you could try moving `menukeys` *after* `hyperref`. If that doesn't work, please update your LaTeX installation and see whether the error still occurs.

**Comment by Semnodime** [comment]
**LaTeX: Minimal Failing Example**
```LaTeX
%% Minimal failing example
\documentclass[
	ngerman,
% 	hidelinks,
%	unicode
	accentcolor=1c,
	type=intern,
	marginpar=false,
	fontsize=11pt,
	]{tudapub}

\usepackage{menukeys}

\begin{document}
test
\end{document}
```
**Some Snippets of the Error Log**
**Note:** *The error log has been somewhat reformatted to remove irrelevant information.*
```
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020) (preloaded format=pdflatex 2020.9.10)
LaTeX2e <2020-02-02> patch level 5
L3 programming layer <2020-07-17>
/usr/local/texlive/2020/texmf-dist/tex/latex/tuda-ci/tudapub.cls
/usr/local/texlive/2020/texmf-dist/tex/latex/l3kernel/expl3.sty

Document Class: tudapub 2020/06/12 v2.11 Publications using TU Darmstadt's Coporate Design (TUDa-CI)

/usr/local/texlive/2020/texmf-dist/tex/latex/hyperref/pd1enc.def
File: pd1enc.def 2020-05-15 v7.00e Hyperref: PDFDocEncoding definition (HO)
Now handling font encoding PD1 ...
... no UTF-8 mapping file for font encoding PD1
/usr/local/texlive/2020/texmf-dist/tex/generic/intcalc/intcalc.sty

Package hyperref Info: Option `unicode' set `true' on input line 4338.
/usr/local/texlive/2020/texmf-dist/tex/latex/hyperref/puenc.def
File: puenc.def 2020-05-15 v7.00e Hyperref: PDF Unicode definition (HO)
Now handling font encoding PU ...
... no UTF-8 mapping file for font encoding PU

Package hyperref Info: Hyper figures OFF on input line 4464.
Package hyperref Info: Link nesting OFF on input line 4469.
Package hyperref Info: Hyper index ON on input line 4472.
Package hyperref Info: Plain pages OFF on input line 4479.
Package hyperref Info: Backreferencing OFF on input line 4484.
Package hyperref Info: Implicit mode ON; LaTeX internals redefined.
Package hyperref Info: Bookmarks ON on input line 4717.
Package hyperref Info: Hyper figures OFF on input line 6347.
Package hyperref Info: Link nesting OFF on input line 6352.
Package hyperref Info: Hyper index ON on input line 6355.
Package hyperref Info: backreferencing OFF on input line 6362.
Package hyperref Info: Link coloring OFF on input line 6367.
Package hyperref Info: Link coloring with OCG OFF on input line 6372.
Package hyperref Info: PDF/A mode OFF on input line 6377.
Package hyperref Info: Driver (autodetected): hpdftex.

/usr/local/texlive/2020/texmf-dist/tex/latex/hyperref/hpdftex.def
File: hpdftex.def 2020-05-15 v7.00e Hyperref driver for pdfTeX

/usr/local/texlive/2020/texmf-dist/tex/latex/atveryend/atveryend.sty
/usr/local/texlive/2020/texmf-dist/tex/latex/menukeys/menukeys.sty

Package: menukeys 2016/08/08 v1.5 -- A package to format menus, paths and shortcuts

(/usr/local/texlive/2020/texmf-dist/tex/latex/bookmark/bookmark.sty
Package: bookmark 2019/12/03 v1.28 PDF bookmarks (HO)

! LaTeX Error: Option clash for package hyperref.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.84 \RequirePackage{hyperref}[2010/06/18]
                                          
The package 'hyperref' has already been loaded with options:
  [hidelinks,unicode].
There has now been an attempt to load it with no options. 
Adding the global options:
  'hidelinks,unicode'
to your \documentclass declaration may fix this. 
```

**Comment by Skillmon** [comment]
Thank you very much for the example and the complete log file up till the error.

You're using `menukeys` version 1.5. The most recent released version is 1.6.1, the first version in which the issues with `hyperref` (and other packages which might have an option clash) were fixed was 1.6. The culprit was one of `menukeys` dependencies (`catoptions`) which changes LaTeX's option handling. Since v1.6 `menukeys` no longer depends on `catoptions`.

Could you please update `menukeys` (you can do so by running `tlmgr update --self --all --reinstall-forcibly-removed`, which updates your complete TeX Live installation to the most recent version)?

**Comment by Semnodime** [comment]
I currently work with LaTeX Live provided by Ovrleaf and thus see no option to update.

I thank you for your explanation regarding the option clash.

As the issue is already fixed in the latest version, waiting for the update to propagate into Overleaf is all I can do for now.

Guess you can close this issue :)

**Comment by Skillmon** [comment]
Overleaf updates only once a year or so for stability reasons.

However you can include single packages in your project. The latest `menukeys` works with Overleaf's current TeX Live image. You can do so by downloading the current release [here](https://github.com/tweh/menukeys/releases/tag/v1.6.1). Unpack the archive and run `pdftex menukeys.ins`. This should result in a file `menukeys.sty` which you can then upload to your project. Compilation on Overleaf will automatically pick that file instead of the old `menukeys` version and you should be good to go.
